spring.application.name=parcial-practica
spring.datasource.url=jdbc:postgresql://localhost:5432/parcial
spring.datasource.username=postgres
spring.datasource.password=saldarriaga1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true